version: "3.8"

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile-Client
    scale: 5
    restart: always
  dockerdemo_server:
    scale: 5
    build:
      context: ./
      dockerfile: Dockerfile-Server
  load-balancer:
    image: nginx:latest
    depends_on:
      - client
      - dockerdemo_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
      - "9900:4000"
